version: '3.1'
 
services:
 
  db:
    image: postgres
    restart: always
    container_name: postgres-refresh-token
    volumes:
     - .volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: authentication
    ports:
      - 5432:5432
 
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080